export interface DrugOrderItem {
  id: string;
  drugName: string;
  dose: number;
  doseUnit: string;
  route: string;
  frequency: string;
  duration: number;
  durationUnit: string;
  instructions?: string;
}

export interface OrderSet {
  id: string;
  name: string;
  category: string;
  description: string;
  drugs: DrugOrderItem[];
}

export const defaultOrderSets: OrderSet[] = [
  {
    id: 'os-pneumonia',
    name: 'Community Acquired Pneumonia',
    category: 'Infectious Disease',
    description: 'Standard treatment for mild-moderate CAP in adults',
    drugs: [
      {
        id: 'd1',
        drugName: 'Amoxicillin',
        dose: 500,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Three times daily',
        duration: 7,
        durationUnit: 'days',
      },
      {
        id: 'd2',
        drugName: 'Azithromycin',
        dose: 500,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 3,
        durationUnit: 'days',
      },
      {
        id: 'd3',
        drugName: 'Paracetamol',
        dose: 1000,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Three times daily',
        duration: 5,
        durationUnit: 'days',
        instructions: 'PRN for fever >38°C',
      },
    ],
  },
  {
    id: 'os-dm2',
    name: 'Type 2 Diabetes – Initial',
    category: 'Endocrinology',
    description: 'First-line therapy for newly diagnosed T2DM',
    drugs: [
      {
        id: 'd4',
        drugName: 'Metformin',
        dose: 500,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Twice daily',
        duration: 30,
        durationUnit: 'days',
        instructions: 'Take with meals',
      },
      {
        id: 'd5',
        drugName: 'Atorvastatin',
        dose: 20,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 30,
        durationUnit: 'days',
        instructions: 'Take at bedtime',
      },
      {
        id: 'd6',
        drugName: 'Lisinopril',
        dose: 10,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 30,
        durationUnit: 'days',
      },
    ],
  },
  {
    id: 'os-malaria',
    name: 'Uncomplicated Malaria',
    category: 'Infectious Disease',
    description: 'ACT-based treatment for P. falciparum malaria',
    drugs: [
      {
        id: 'd7',
        drugName: 'Artemether-Lumefantrine',
        dose: 80,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Twice daily',
        duration: 3,
        durationUnit: 'days',
        instructions: 'Take with fatty food',
      },
      {
        id: 'd8',
        drugName: 'Paracetamol',
        dose: 1000,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Three times daily',
        duration: 3,
        durationUnit: 'days',
        instructions: 'PRN for fever',
      },
    ],
  },
  {
    id: 'os-hypertension',
    name: 'Hypertension – Step 1',
    category: 'Cardiology',
    description: 'Initial antihypertensive therapy',
    drugs: [
      {
        id: 'd9',
        drugName: 'Amlodipine',
        dose: 5,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 30,
        durationUnit: 'days',
      },
      {
        id: 'd10',
        drugName: 'Lisinopril',
        dose: 10,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 30,
        durationUnit: 'days',
      },
    ],
  },
  {
    id: 'os-cellulitis',
    name: 'Cellulitis',
    category: 'Infectious Disease',
    description: 'Skin and soft tissue infection treatment',
    drugs: [
      {
        id: 'd27',
        drugName: 'Ceftriaxone',
        dose: 1,
        doseUnit: 'g',
        route: 'IV',
        frequency: 'Once daily',
        duration: 5,
        durationUnit: 'days',
      },
      {
        id: 'd28',
        drugName: 'Paracetamol',
        dose: 1000,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Three times daily',
        duration: 5,
        durationUnit: 'days',
      },
    ],
  },
  {
    id: 'os-gastritis',
    name: 'Acute Gastritis / PUD',
    category: 'Gastroenterology',
    description: 'Standard triple therapy for H. pylori with PPI cover',
    drugs: [
      {
        id: 'd11',
        drugName: 'Omeprazole',
        dose: 20,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Twice daily',
        duration: 14,
        durationUnit: 'days',
        instructions: 'Take 30 min before meals',
      },
      {
        id: 'd12',
        drugName: 'Amoxicillin',
        dose: 1000,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Twice daily',
        duration: 14,
        durationUnit: 'days',
      },
      {
        id: 'd13',
        drugName: 'Metronidazole',
        dose: 500,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Twice daily',
        duration: 14,
        durationUnit: 'days',
      },
    ],
  },
  {
    id: 'os-sepsis',
    name: 'Sepsis – Empiric',
    category: 'Emergency',
    description: 'Empiric antibiotics for suspected sepsis',
    drugs: [
      {
        id: 'd14',
        drugName: 'Ceftriaxone',
        dose: 2,
        doseUnit: 'g',
        route: 'IV',
        frequency: 'Once daily',
        duration: 7,
        durationUnit: 'days',
      },
      {
        id: 'd15',
        drugName: 'Metronidazole',
        dose: 500,
        doseUnit: 'mg',
        route: 'IV',
        frequency: 'Every 8 hours',
        duration: 7,
        durationUnit: 'days',
      },
      {
        id: 'd16',
        drugName: 'Normal Saline',
        dose: 1000,
        doseUnit: 'mL',
        route: 'IV',
        frequency: 'Every 8 hours',
        duration: 1,
        durationUnit: 'days',
        instructions: 'Bolus if hypotensive',
      },
      {
        id: 'd17',
        drugName: 'Paracetamol',
        dose: 1000,
        doseUnit: 'mg',
        route: 'IV',
        frequency: 'Every 6 hours',
        duration: 3,
        durationUnit: 'days',
        instructions: 'PRN for fever',
      },
    ],
  },
  {
    id: 'os-asthma',
    name: 'Acute Asthma Exacerbation',
    category: 'Pulmonology',
    description: 'Acute management of moderate asthma flare',
    drugs: [
      {
        id: 'd18',
        drugName: 'Salbutamol',
        dose: 2,
        doseUnit: 'puffs',
        route: 'Inhaled',
        frequency: 'Every 6 hours',
        duration: 5,
        durationUnit: 'days',
      },
      {
        id: 'd19',
        drugName: 'Prednisolone',
        dose: 40,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 5,
        durationUnit: 'days',
        instructions: 'Take in the morning',
      },
      {
        id: 'd20',
        drugName: 'Omeprazole',
        dose: 20,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 5,
        durationUnit: 'days',
        instructions: 'Gastroprotection while on steroids',
      },
    ],
  },
  {
    id: 'os-dka',
    name: 'Diabetic Ketoacidosis',
    category: 'Endocrinology',
    description: 'Initial management of diabetic ketoacidosis',
    drugs: [
      {
        id: 'd45',
        drugName: 'Normal Saline',
        dose: 1000,
        doseUnit: 'mL',
        route: 'IV',
        frequency: 'Every 6 hours',
        duration: 1,
        durationUnit: 'days',
        instructions: 'Initial fluid resuscitation',
      },
      {
        id: 'd46',
        drugName: 'Insulin Glargine',
        dose: 10,
        doseUnit: 'units',
        route: 'SC',
        frequency: 'Once daily',
        duration: 5,
        durationUnit: 'days',
      },
      {
        id: 'd47',
        drugName: 'Ringer\'s Lactate',
        dose: 1000,
        doseUnit: 'mL',
        route: 'IV',
        frequency: 'Every 8 hours',
        duration: 1,
        durationUnit: 'days',
      },
    ],
  },

  {
    id: 'os-hypoglycemia',
    name: 'Hypoglycemia Management',
    category: 'Endocrinology',
    description: 'Treatment for symptomatic hypoglycemia',
    drugs: [
      {
        id: 'd48',
        drugName: 'Dextrose',
        dose: 50,
        doseUnit: 'mL',
        route: 'IV',
        frequency: 'Stat',
        duration: 1,
        durationUnit: 'days',
        instructions: '50% dextrose bolus',
      },
      {
        id: 'd49',
        drugName: 'Normal Saline',
        dose: 500,
        doseUnit: 'mL',
        route: 'IV',
        frequency: 'Once',
        duration: 1,
        durationUnit: 'days',
      },
    ],
  },

  {
    id: 'os-hyperthyroidism',
    name: 'Hyperthyroidism',
    category: 'Endocrinology',
    description: 'Initial management of hyperthyroidism',
    drugs: [
      {
        id: 'd51',
        drugName: 'Propranolol',
        dose: 40,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Twice daily',
        duration: 30,
        durationUnit: 'days',
        instructions: 'For symptom control',
      },
      {
        id: 'd52',
        drugName: 'Carbimazole',
        dose: 10,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Three times daily',
        duration: 30,
        durationUnit: 'days',
      },
    ],
  },

  {
    id: 'os-diabetes-insulin',
    name: 'Type 2 Diabetes – Insulin Therapy',
    category: 'Endocrinology',
    description: 'Escalation to basal insulin therapy',
    drugs: [
      {
        id: 'd53',
        drugName: 'Insulin Glargine',
        dose: 10,
        doseUnit: 'units',
        route: 'SC',
        frequency: 'Once daily',
        duration: 30,
        durationUnit: 'days',
        instructions: 'Administer at bedtime',
      },
      {
        id: 'd54',
        drugName: 'Metformin',
        dose: 1000,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Twice daily',
        duration: 30,
        durationUnit: 'days',
        instructions: 'Take with meals',
      },
      {
        id: 'd55',
        drugName: 'Atorvastatin',
        dose: 20,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 30,
        durationUnit: 'days',
        instructions: 'Take at bedtime',
      },
    ],
  },
  {
    id: 'os-heart-failure',
    name: 'Congestive Heart Failure',
    category: 'Cardiology',
    description: 'Initial management of CHF',
    drugs: [
      {
        id: 'd32',
        drugName: 'Furosemide',
        dose: 40,
        doseUnit: 'mg',
        route: 'IV',
        frequency: 'Once daily',
        duration: 5,
        durationUnit: 'days',
      },
      {
        id: 'd33',
        drugName: 'Lisinopril',
        dose: 10,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Once daily',
        duration: 30,
        durationUnit: 'days',
      },
    ],
  },
  {
    id: 'os-pain',
    name: 'Post-Op Pain Management',
    category: 'Surgery',
    description: 'Multimodal analgesia after minor surgery',
    drugs: [
      {
        id: 'd21',
        drugName: 'Paracetamol',
        dose: 1000,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Four times daily',
        duration: 5,
        durationUnit: 'days',
      },
      {
        id: 'd22',
        drugName: 'Ibuprofen',
        dose: 400,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Three times daily',
        duration: 5,
        durationUnit: 'days',
        instructions: 'Take with food',
      },
      {
        id: 'd23',
        drugName: 'Tramadol',
        dose: 50,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Every 8 hours',
        duration: 3,
        durationUnit: 'days',
        instructions: 'PRN for breakthrough pain',
      },
      {
        id: 'd24',
        drugName: 'Ondansetron',
        dose: 4,
        doseUnit: 'mg',
        route: 'Oral',
        frequency: 'Every 8 hours',
        duration: 3,
        durationUnit: 'days',
        instructions: 'PRN for nausea',
      },
    ],
  },
];

export const availableDrugs = [
  'Amoxicillin',
  'Azithromycin',
  'Metformin',
  'Lisinopril',
  'Amlodipine',
  'Atorvastatin',
  'Omeprazole',
  'Paracetamol',
  'Ibuprofen',
  'Diclofenac',
  'Metronidazole',
  'Ciprofloxacin',
  'Ceftriaxone',
  'Doxycycline',
  'Prednisolone',
  'Salbutamol',
  'Insulin Glargine',
  'Furosemide',
  'Aspirin',
  'Clopidogrel',
  'Enoxaparin',
  'Morphine',
  'Tramadol',
  'Ondansetron',
  'Ranitidine',
  'ORS',
  'Zinc',
  'Artemether-Lumefantrine',
  'Chloroquine',
  'Quinine',
  'Hydrocortisone',
  'Dexamethasone',
  'Normal Saline',
  "Ringer's Lactate",
];
